version: '3.8'

services:
  api:
    container_name: travel-planner-api
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  postgres-db:
    image: postgres:16
    container_name: travel-planner-postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.development
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2
    container_name: travel-planner-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.development
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
    pg_data:
    redis_data:
