"""add field city and country

Revision ID: 3e7a63f3c06a
Revises: 344e0e325435
Create Date: 2024-11-29 13:24:38.700025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7a63f3c06a'
down_revision: Union[str, None] = '344e0e325435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('city', sa.String(), nullable=True))
    op.add_column('places', sa.Column('country', sa.String(), nullable=True))
    op.add_column('planned_places', sa.Column('city', sa.String(), nullable=True))
    op.add_column('planned_places', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_places', 'country')
    op.drop_column('planned_places', 'city')
    op.drop_column('places', 'country')
    op.drop_column('places', 'city')
    # ### end Alembic commands ###
